/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;

import edu.princeton.cs.algs4.Draw;

public class App {
    
    Draw draw;

    public App(){

        this.draw = new Draw();
        this.draw.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);

        // Ajusta o tamanho da tela usando algum método do objeto Draw
        this.draw.setCanvasSize(1000, 600);

        // Ajusta a escala X usando algum outro método do objeto Draw
        this.draw.setXscale(0.0f, 1000.0f);

        // Ajusta a escala Y usando ainda outro método do objeto Draw
        this.draw.setYscale(0.0f, 600.0f);

    }

    public static void main(String[] args) {
        
        App app = new App();
        Grade grade = new Grade(100, 100);
        grade.desenhar(app.draw);

        double[] pos = {6, 2};
        Navio navio = new Navio(1, false, pos);
        navio.desenhar(app.draw, grade);
        app.draw.show();

    }
}